import { useEffect, useMemo } from 'react';
import createBattleInputController from '../input/BattleInputController';

export default function useBattleSceneInputController({
  open = false,
  interactionLocked = false,
  glCanvasRef,
  runtimeRef,
  cameraRef,
  worldToScreenRef,
  pointerWorldRef,
  panDragRef,
  deployYawDragRef,
  deployRectDragRef,
  spacePressedRef,
  selectedSquadId = '',
  battleUiMode = '',
  skillConfirmState = null,
  aimState = null,
  deployDraggingGroupId = '',
  deployDraggingTeam = 'attacker',
  selectedPaletteItemId = '',
  isTrainingMode = false,
  isPathPointBlocked,
  syncBattleCards,
  selectBattleSquad,
  closeSkillConfirm,
  closeSkillPick,
  closeSpacingPick,
  recallDeployDraggingGroup,
  setClockPaused,
  setCards,
  setMinimapSnapshot,
  setIsPanning,
  setDeployNotice,
  setSelectedSquadId,
  setDeployDraggingGroup,
  setDeployActionAnchorMode,
  setPendingPathPoints,
  setPlanningHoverPoint,
  setBattleUiMode,
  setSkillPopupSquadId,
  setAimState,
  setSkillConfirmState,
  setWorldActionsVisibleForSquadId,
  ORDER_MOVE,
  CAMERA_ZOOM_STEP,
  CAMERA_DISTANCE_CLOSE_MIN,
  CAMERA_DISTANCE_MIN,
  CAMERA_DISTANCE_MAX,
  TRAINING_OVERVIEW_DISTANCE_EXTRA,
  TRAINING_OVERVIEW_DISTANCE_MAX,
  TRAINING_OVERVIEW_VIEW_PADDING,
  DEPLOY_ROTATE_SENSITIVITY,
  DEPLOY_ROTATE_CLICK_THRESHOLD,
  DEPLOY_WHEEL_ROTATE_STEP_DEG,
  DEPLOY_PITCH_DEG,
  BATTLE_UI_MODE_NONE,
  BATTLE_UI_MODE_PATH,
  BATTLE_UI_MODE_SPACING_PICK,
  BATTLE_UI_MODE_SKILL_PICK,
  BATTLE_UI_MODE_SKILL_CONFIRM,
  skillRangeByClass,
  skillAoeRadiusByClass
} = {}) {
  const battleInputController = useMemo(() => createBattleInputController({
    open,
    interactionLocked,
    canvasRef: glCanvasRef,
    runtimeRef,
    cameraControllerRef: cameraRef,
    worldToScreenRef,
    pointerWorldRef,
    panDragRef,
    deployYawDragRef,
    deployRectDragRef,
    spacePressedRef,
    constants: {
      ORDER_MOVE,
      CAMERA_ZOOM_STEP,
      CAMERA_DISTANCE_CLOSE_MIN,
      CAMERA_DISTANCE_MIN,
      CAMERA_DISTANCE_MAX,
      TRAINING_OVERVIEW_DISTANCE_EXTRA,
      TRAINING_OVERVIEW_DISTANCE_MAX,
      TRAINING_OVERVIEW_VIEW_PADDING,
      DEPLOY_ROTATE_SENSITIVITY,
      DEPLOY_ROTATE_CLICK_THRESHOLD,
      DEPLOY_WHEEL_ROTATE_STEP_DEG,
      DEPLOY_PITCH_DEG,
      BATTLE_UI_MODE_NONE,
      BATTLE_UI_MODE_PATH,
      BATTLE_UI_MODE_SPACING_PICK,
      BATTLE_UI_MODE_SKILL_PICK,
      BATTLE_UI_MODE_SKILL_CONFIRM,
      skillRangeByClass,
      skillAoeRadiusByClass
    },
    getters: {
      getSelectedSquadId: () => selectedSquadId,
      getBattleUiMode: () => battleUiMode,
      getSkillConfirmState: () => skillConfirmState,
      getAimState: () => aimState,
      getDeployDraggingGroupId: () => deployDraggingGroupId,
      getDeployDraggingTeam: () => deployDraggingTeam,
      getSelectedPaletteItemId: () => selectedPaletteItemId,
      isTrainingMode: () => isTrainingMode
    },
    callbacks: {
      setIsPanning,
      setCards,
      setMinimapSnapshot,
      setDeployNotice,
      setSelectedSquadId,
      setDeployDraggingGroup,
      setDeployActionAnchorMode,
      setPendingPathPoints,
      setPlanningHoverPoint,
      setBattleUiMode,
      setSkillPopupSquadId,
      setClockPaused,
      setAimState,
      setSkillConfirmState,
      setWorldActionsVisibleForSquadId,
      isPathPointBlocked,
      syncBattleCards,
      selectBattleSquad,
      closeSkillConfirm,
      closeSkillPick,
      closeSpacingPick,
      recallDeployDraggingGroup
    }
  }), [
    open,
    interactionLocked,
    runtimeRef,
    worldToScreenRef,
    selectedSquadId,
    battleUiMode,
    skillConfirmState,
    aimState,
    deployDraggingGroupId,
    deployDraggingTeam,
    selectedPaletteItemId,
    isTrainingMode,
    isPathPointBlocked,
    syncBattleCards,
    selectBattleSquad,
    closeSkillConfirm,
    closeSkillPick,
    closeSpacingPick,
    recallDeployDraggingGroup,
    setClockPaused,
    setCards,
    setMinimapSnapshot,
    glCanvasRef,
    cameraRef,
    pointerWorldRef,
    panDragRef,
    deployYawDragRef,
    deployRectDragRef,
    spacePressedRef,
    setIsPanning,
    setDeployNotice,
    setSelectedSquadId,
    setDeployDraggingGroup,
    setDeployActionAnchorMode,
    setPendingPathPoints,
    setPlanningHoverPoint,
    setBattleUiMode,
    setSkillPopupSquadId,
    setAimState,
    setSkillConfirmState,
    setWorldActionsVisibleForSquadId,
    ORDER_MOVE,
    CAMERA_ZOOM_STEP,
    CAMERA_DISTANCE_CLOSE_MIN,
    CAMERA_DISTANCE_MIN,
    CAMERA_DISTANCE_MAX,
    TRAINING_OVERVIEW_DISTANCE_EXTRA,
    TRAINING_OVERVIEW_DISTANCE_MAX,
    TRAINING_OVERVIEW_VIEW_PADDING,
    DEPLOY_ROTATE_SENSITIVITY,
    DEPLOY_ROTATE_CLICK_THRESHOLD,
    DEPLOY_WHEEL_ROTATE_STEP_DEG,
    DEPLOY_PITCH_DEG,
    BATTLE_UI_MODE_NONE,
    BATTLE_UI_MODE_PATH,
    BATTLE_UI_MODE_SPACING_PICK,
    BATTLE_UI_MODE_SKILL_PICK,
    BATTLE_UI_MODE_SKILL_CONFIRM,
    skillRangeByClass,
    skillAoeRadiusByClass
  ]);

  useEffect(() => {
    if (!open) return undefined;
    return battleInputController.bindWindow();
  }, [open, battleInputController]);

  useEffect(() => {
    if (!interactionLocked) return;
    battleInputController.clearPanDrag();
    battleInputController.clearDeployYawDrag();
    battleInputController.clearDeployRectDrag();
    runtimeRef.current?.setHoveredDeployGroup?.('');
  }, [battleInputController, interactionLocked, runtimeRef]);

  return {
    onDoubleClick: battleInputController.onDoubleClick,
    onMouseDown: battleInputController.onMouseDown,
    onMouseMove: battleInputController.onMouseMove,
    onMouseLeave: battleInputController.onMouseLeave,
    onWheel: battleInputController.onWheel,
    onContextMenu: battleInputController.onContextMenu,
    onMinimapClick: battleInputController.onMinimapClick
  };
}
