const MAX_FRIEND_COUNT = 200;
const MAX_GROUP_CREATED_COUNT = 3;
const MAX_GROUP_MEMBERSHIP_COUNT = 10;
const MAX_GROUP_MEMBER_COUNT = 50;
const MAX_GROUP_SHARE_TARGET_COUNT = 20;
const MAX_GROUP_TITLE_LENGTH = 40;
const MAX_GROUP_ANNOUNCEMENT_LENGTH = 300;
const MAX_DIRECT_MESSAGE_LENGTH = 2000;
const MAX_NON_FRIEND_DIRECT_MESSAGES = 3;
const GROUP_NO_LENGTH = 10;
const GROUP_NO_SEQUENCE_KEY = 'chat:group-no';
const GROUP_NO_SEQUENCE_START = 1000000000;
const DEFAULT_GROUP_AVATAR = 'group_general';
const GROUP_AVATAR_KEYS = Object.freeze([
  DEFAULT_GROUP_AVATAR,
  'group_study',
  'group_social',
  'group_gaming',
  'group_project',
  'group_news'
]);

module.exports = {
  DEFAULT_GROUP_AVATAR,
  GROUP_NO_LENGTH,
  GROUP_AVATAR_KEYS,
  GROUP_NO_SEQUENCE_KEY,
  GROUP_NO_SEQUENCE_START,
  MAX_DIRECT_MESSAGE_LENGTH,
  MAX_FRIEND_COUNT,
  MAX_GROUP_ANNOUNCEMENT_LENGTH,
  MAX_GROUP_CREATED_COUNT,
  MAX_GROUP_MEMBER_COUNT,
  MAX_GROUP_SHARE_TARGET_COUNT,
  MAX_GROUP_MEMBERSHIP_COUNT,
  MAX_GROUP_TITLE_LENGTH,
  MAX_NON_FRIEND_DIRECT_MESSAGES
};
