const MAX_FRIEND_COUNT = 200;
const MAX_GROUP_MEMBERSHIP_COUNT = 10;
const MAX_GROUP_MEMBER_COUNT = 50;
const MAX_GROUP_TITLE_LENGTH = 40;
const MAX_GROUP_ANNOUNCEMENT_LENGTH = 300;
const MAX_DIRECT_MESSAGE_LENGTH = 2000;
const MAX_NON_FRIEND_DIRECT_MESSAGES = 3;

module.exports = {
  MAX_DIRECT_MESSAGE_LENGTH,
  MAX_FRIEND_COUNT,
  MAX_GROUP_ANNOUNCEMENT_LENGTH,
  MAX_GROUP_MEMBER_COUNT,
  MAX_GROUP_MEMBERSHIP_COUNT,
  MAX_GROUP_TITLE_LENGTH,
  MAX_NON_FRIEND_DIRECT_MESSAGES
};
