const MAX_FRIEND_COUNT = 200;
const MAX_GROUP_MEMBERSHIP_COUNT = 10;
const MAX_DIRECT_MESSAGE_LENGTH = 2000;

module.exports = {
  MAX_DIRECT_MESSAGE_LENGTH,
  MAX_FRIEND_COUNT,
  MAX_GROUP_MEMBERSHIP_COUNT
};
