import React from 'react';
import AdminNodesTab from './components/AdminNodesTab';
import AdminEditNodeModal from './components/AdminEditNodeModal';
import AdminAddSenseModal from './components/AdminAddSenseModal';
import AdminDeleteSenseModal from './components/AdminDeleteSenseModal';
import AdminDeleteSenseDecisionModal from './components/AdminDeleteSenseDecisionModal';
import AdminDeleteNodeModal from './components/AdminDeleteNodeModal';
import AdminChangeMasterModal from './components/AdminChangeMasterModal';
import AdminEditAssociationModal from './components/AdminEditAssociationModal';
import AdminAssocDeleteDecisionModal from './components/AdminAssocDeleteDecisionModal';

const AdminNodesFeature = ({
    isActive,
    showEditNodeModal,
    editingNode,
    editNodeForm,
    isSavingNodeEdit,
    setEditNodeForm,
    closeEditNodeModal,
    saveNodeEdit,
    showAddSenseModal,
    addingSenseNode,
    isSavingNewSense,
    newSenseForm,
    newSenseAssocFlow,
    assocSteps,
    assocRelationTypes,
    relSymbolSubset,
    relSymbolSuperset,
    newSenseAssocSourceDisplay,
    newSenseAssocTargetDisplay,
    newSenseAssocSecondTargetDisplay,
    newSenseAssocNodeASenseOptions,
    newSenseAssocInsertRelationAvailable,
    newSenseAssocInsertRelationUnavailableReason,
    newSenseAssocNodeBCandidateView,
    newSenseAssocPreviewCanvasRef,
    newSenseAssocPreviewInfoText,
    setNewSenseForm,
    setNewSenseAssocFlow,
    closeAddSenseModal,
    removeRelationFromNewSense,
    searchNewSenseAssocNodeA,
    clearNewSenseAssocNodeASearch,
    selectNewSenseAssocNodeA,
    handleNewSenseAssocNodeASenseChange,
    selectNewSenseAssocRelationType,
    submitNewSenseAssocNodeBSearch,
    selectNewSenseAssocNodeB,
    confirmNewSenseAssocRelation,
    goBackNewSenseAssocStep,
    cancelNewSenseAssocFlow,
    startNewSenseRelationEditor,
    saveNewSense,
    showDeleteSenseModal,
    deletingSenseContext,
    deleteSenseWillDeleteNode,
    deleteSenseBeforeRelations,
    deleteSenseAfterRelations,
    deleteSensePreviewLoading,
    deleteSenseLostBridgePairs,
    deleteSensePendingBridgePairs,
    deleteSenseConfirmedBridgePairs,
    deleteSensePreviewData,
    isDeletingSense,
    formatRelationArrowText,
    resolveDeleteBridgePairMode,
    resolveDecisionPairSideDisplay,
    resolveDecisionCurrentDisplay,
    openDeleteSenseDecisionModal,
    rollbackDeleteSensePairDecision,
    closeDeleteSenseModal,
    deleteSense,
    showDeleteSenseDecisionModal,
    deleteSenseDecisionPair,
    deleteSenseDecisionApplying,
    applyDeleteSensePairDecision,
    closeDeleteSenseDecisionModal,
    showDeleteNodeConfirmModal,
    deletingNodeTarget,
    deletePreviewSummary,
    deleteBeforeRelations,
    deleteAfterRelations,
    deletingNodePreview,
    deletePreviewLoading,
    deletePreviewData,
    deleteLostBridgePairs,
    deleteBridgeDecisions,
    isDeletingNode,
    handleDeleteNodeBridgeDecision,
    closeDeleteNodeConfirmModal,
    deleteNode,
    showChangeMasterModal,
    changingMasterNode,
    masterSearchKeyword,
    masterSearchResults,
    isMasterSearchLoading,
    hasMasterSearchTriggered,
    selectedNewMaster,
    setMasterSearchKeyword,
    setMasterSearchResults,
    setHasMasterSearchTriggered,
    setSelectedNewMaster,
    searchUsersForMaster,
    confirmChangeMaster,
    setShowChangeMasterModal,
    showEditAssociationModal,
    editingAssociationNode,
    editingAssociationSenseId,
    editAssociations,
    isEditAssociationListExpanded,
    assocCurrentStep,
    assocSelectedRelationType,
    assocSelectedSourceSenseId,
    assocSelectedNodeA,
    assocSelectedNodeASenseId,
    assocSelectedNodeB,
    assocSelectedNodeBSenseId,
    assocInsertDirection,
    assocNodeASenseOptions,
    assocInsertRelationAvailable,
    assocInsertRelationUnavailableReason,
    assocSearchKeyword,
    assocSearchAppliedKeyword,
    assocSearchLoading,
    assocSearchResults,
    assocNodeBView,
    assocNodeBSearchAppliedKeyword,
    assocNodeBSearchKeyword,
    assocPreviewCanvasRef,
    assocPreviewInfoText,
    assocApplyLoading,
    formatNodeSenseDisplay,
    resolveAssociationDisplayType,
    setIsEditAssociationListExpanded,
    setAssocSearchKeyword,
    searchAssociationNodes,
    clearAssocNodeASearch,
    selectAssocNodeA,
    handleAssocNodeASenseChange,
    selectAssocRelationType,
    submitAssocNodeBSearch,
    selectAssocNodeB,
    confirmEditAssociation,
    goBackAssocStep,
    resetAssociationEditor,
    startAddEditAssociation,
    editExistingAssociation,
    removeEditAssociation,
    saveAssociationEdit,
    closeEditAssociationModal,
    showAssocDeleteDecisionModal,
    assocDeleteDecisionContext,
    assocDeleteDecisionAction,
    assocDeleteApplying,
    assocDeleteSelectedTarget,
    assocDeleteReplacementDisplay,
    shouldShowAssocDeleteSearch,
    assocDeleteSearchKeyword,
    assocDeleteSearchAppliedKeyword,
    assocDeleteSearchResults,
    assocDeleteSearchLoading,
    setAssocDeleteDecisionAction,
    setAssocDeleteSearchKeyword,
    setAssocDeleteSelectedTarget,
    searchAssocDeleteTargets,
    confirmAssocDeleteDecision,
    clearAssocDeleteSearch,
    closeAssocDeleteDecisionModal,
    adminDomainPagination,
    adminDomainPageSize,
    pageSizeOptions,
    isAdminDomainLoading,
    adminDomainSearchInput,
    adminDomainSearchKeyword,
    hierarchicalNodeList,
    editingSenseToken,
    editingSenseForm,
    editingSenseActionToken,
    setAdminDomainSearchInput,
    setEditingSenseForm,
    getSenseEditToken,
    getEditableSenseAssociationCount,
    onCreateNode,
    handleAdminDomainPageSizeChange,
    submitAdminDomainSearch,
    clearAdminDomainSearch,
    refreshAdminDomainLatest,
    openChangeMasterModal,
    toggleFeaturedNode,
    startEditNode,
    openAddSenseModal,
    openDeleteNodeConfirmModal,
    saveSenseTextEdit,
    cancelEditSenseText,
    startEditSenseText,
    openEditAssociationModal,
    openDeleteSenseModal,
    fetchAllNodes
}) => (
    <>
        {isActive && (
            <AdminNodesTab
                adminDomainPagination={adminDomainPagination}
                adminDomainPageSize={adminDomainPageSize}
                pageSizeOptions={pageSizeOptions}
                isAdminDomainLoading={isAdminDomainLoading}
                adminDomainSearchInput={adminDomainSearchInput}
                adminDomainSearchKeyword={adminDomainSearchKeyword}
                hierarchicalNodeList={hierarchicalNodeList}
                editingSenseToken={editingSenseToken}
                editingSenseForm={editingSenseForm}
                editingSenseActionToken={editingSenseActionToken}
                setAdminDomainSearchInput={setAdminDomainSearchInput}
                setEditingSenseForm={setEditingSenseForm}
                getSenseEditToken={getSenseEditToken}
                getEditableSenseAssociationCount={getEditableSenseAssociationCount}
                onCreateNode={onCreateNode}
                onAdminDomainPageSizeChange={handleAdminDomainPageSizeChange}
                onSubmitAdminDomainSearch={submitAdminDomainSearch}
                onClearAdminDomainSearch={clearAdminDomainSearch}
                onRefreshAdminDomainLatest={refreshAdminDomainLatest}
                onOpenChangeMasterModal={openChangeMasterModal}
                onToggleFeaturedNode={toggleFeaturedNode}
                onStartEditNode={startEditNode}
                onOpenAddSenseModal={openAddSenseModal}
                onOpenDeleteNodeConfirmModal={openDeleteNodeConfirmModal}
                onSaveSenseTextEdit={saveSenseTextEdit}
                onCancelEditSenseText={cancelEditSenseText}
                onStartEditSenseText={startEditSenseText}
                onOpenEditAssociationModal={openEditAssociationModal}
                onOpenDeleteSenseModal={openDeleteSenseModal}
                onPrevPage={() => fetchAllNodes(adminDomainPagination.page - 1, adminDomainSearchKeyword)}
                onNextPage={() => fetchAllNodes(adminDomainPagination.page + 1, adminDomainSearchKeyword)}
            />
        )}
        {showEditNodeModal && editingNode && (
            <AdminEditNodeModal
                editingNode={editingNode}
                editNodeForm={editNodeForm}
                isSavingNodeEdit={isSavingNodeEdit}
                setEditNodeForm={setEditNodeForm}
                onClose={closeEditNodeModal}
                onSave={() => saveNodeEdit(editingNode)}
            />
        )}
        {showAddSenseModal && addingSenseNode && (
            <AdminAddSenseModal
                addingSenseNode={addingSenseNode}
                isSavingNewSense={isSavingNewSense}
                newSenseForm={newSenseForm}
                newSenseAssocFlow={newSenseAssocFlow}
                assocSteps={assocSteps}
                assocRelationTypes={assocRelationTypes}
                relSymbolSubset={relSymbolSubset}
                relSymbolSuperset={relSymbolSuperset}
                newSenseAssocSourceDisplay={newSenseAssocSourceDisplay}
                newSenseAssocTargetDisplay={newSenseAssocTargetDisplay}
                newSenseAssocSecondTargetDisplay={newSenseAssocSecondTargetDisplay}
                newSenseAssocNodeASenseOptions={newSenseAssocNodeASenseOptions}
                newSenseAssocInsertRelationAvailable={newSenseAssocInsertRelationAvailable}
                newSenseAssocInsertRelationUnavailableReason={newSenseAssocInsertRelationUnavailableReason}
                newSenseAssocNodeBCandidateView={newSenseAssocNodeBCandidateView}
                newSenseAssocPreviewCanvasRef={newSenseAssocPreviewCanvasRef}
                newSenseAssocPreviewInfoText={newSenseAssocPreviewInfoText}
                setNewSenseForm={setNewSenseForm}
                setNewSenseAssocFlow={setNewSenseAssocFlow}
                onClose={closeAddSenseModal}
                onRemoveRelationFromNewSense={removeRelationFromNewSense}
                onSearchNewSenseAssocNodeA={searchNewSenseAssocNodeA}
                onClearNewSenseAssocNodeASearch={clearNewSenseAssocNodeASearch}
                onSelectNewSenseAssocNodeA={selectNewSenseAssocNodeA}
                onHandleNewSenseAssocNodeASenseChange={handleNewSenseAssocNodeASenseChange}
                onSelectNewSenseAssocRelationType={selectNewSenseAssocRelationType}
                onSubmitNewSenseAssocNodeBSearch={submitNewSenseAssocNodeBSearch}
                onSelectNewSenseAssocNodeB={selectNewSenseAssocNodeB}
                onConfirmNewSenseAssocRelation={confirmNewSenseAssocRelation}
                onGoBackNewSenseAssocStep={goBackNewSenseAssocStep}
                onCancelNewSenseAssocFlow={cancelNewSenseAssocFlow}
                onStartNewSenseRelationEditor={startNewSenseRelationEditor}
                onSaveNewSense={saveNewSense}
            />
        )}
        {showDeleteSenseModal && deletingSenseContext?.node && deletingSenseContext?.sense && (
            <AdminDeleteSenseModal
                deletingSenseContext={deletingSenseContext}
                deleteSenseWillDeleteNode={deleteSenseWillDeleteNode}
                deleteSenseBeforeRelations={deleteSenseBeforeRelations}
                deleteSenseAfterRelations={deleteSenseAfterRelations}
                deleteSensePreviewLoading={deleteSensePreviewLoading}
                deleteSenseLostBridgePairs={deleteSenseLostBridgePairs}
                deleteSensePendingBridgePairs={deleteSensePendingBridgePairs}
                deleteSenseConfirmedBridgePairs={deleteSenseConfirmedBridgePairs}
                deleteSensePreviewData={deleteSensePreviewData}
                isDeletingSense={isDeletingSense}
                formatRelationArrowText={formatRelationArrowText}
                resolveDeleteBridgePairMode={resolveDeleteBridgePairMode}
                resolveDecisionPairSideDisplay={resolveDecisionPairSideDisplay}
                resolveDecisionCurrentDisplay={resolveDecisionCurrentDisplay}
                openDeleteSenseDecisionModal={openDeleteSenseDecisionModal}
                rollbackDeleteSensePairDecision={rollbackDeleteSensePairDecision}
                onClose={closeDeleteSenseModal}
                onDelete={deleteSense}
            />
        )}
        {showDeleteSenseDecisionModal && deleteSenseDecisionPair && deletingSenseContext?.node && (
            <AdminDeleteSenseDecisionModal
                deletingSenseContext={deletingSenseContext}
                deleteSenseDecisionPair={deleteSenseDecisionPair}
                deleteSenseBeforeRelations={deleteSenseBeforeRelations}
                deleteSenseDecisionApplying={deleteSenseDecisionApplying}
                deleteSensePreviewLoading={deleteSensePreviewLoading}
                isDeletingSense={isDeletingSense}
                resolveDeleteBridgePairMode={resolveDeleteBridgePairMode}
                resolveDecisionPairSideDisplay={resolveDecisionPairSideDisplay}
                resolveDecisionCurrentDisplay={resolveDecisionCurrentDisplay}
                applyDeleteSensePairDecision={applyDeleteSensePairDecision}
                onClose={closeDeleteSenseDecisionModal}
            />
        )}
        {showDeleteNodeConfirmModal && deletingNodeTarget && (
            <AdminDeleteNodeModal
                deletingNodeTarget={deletingNodeTarget}
                deletePreviewSummary={deletePreviewSummary}
                deleteBeforeRelations={deleteBeforeRelations}
                deleteAfterRelations={deleteAfterRelations}
                deletingNodePreview={deletingNodePreview}
                deletePreviewLoading={deletePreviewLoading}
                deletePreviewData={deletePreviewData}
                deleteLostBridgePairs={deleteLostBridgePairs}
                deleteBridgeDecisions={deleteBridgeDecisions}
                isDeletingNode={isDeletingNode}
                formatRelationArrowText={formatRelationArrowText}
                handleDeleteNodeBridgeDecision={handleDeleteNodeBridgeDecision}
                resolveDecisionCurrentDisplay={resolveDecisionCurrentDisplay}
                resolveDecisionPairSideDisplay={resolveDecisionPairSideDisplay}
                onClose={closeDeleteNodeConfirmModal}
                onDelete={deleteNode}
            />
        )}
        {showChangeMasterModal && changingMasterNode && (
            <AdminChangeMasterModal
                changingMasterNode={changingMasterNode}
                masterSearchKeyword={masterSearchKeyword}
                masterSearchResults={masterSearchResults}
                isMasterSearchLoading={isMasterSearchLoading}
                hasMasterSearchTriggered={hasMasterSearchTriggered}
                selectedNewMaster={selectedNewMaster}
                setMasterSearchKeyword={setMasterSearchKeyword}
                setMasterSearchResults={setMasterSearchResults}
                setHasMasterSearchTriggered={setHasMasterSearchTriggered}
                setSelectedNewMaster={setSelectedNewMaster}
                searchUsersForMaster={searchUsersForMaster}
                confirmChangeMaster={confirmChangeMaster}
                onClose={() => setShowChangeMasterModal(false)}
            />
        )}
        {showEditAssociationModal && editingAssociationNode && (
            <AdminEditAssociationModal
                editingAssociationNode={editingAssociationNode}
                editingAssociationSenseId={editingAssociationSenseId}
                editAssociations={editAssociations}
                isEditAssociationListExpanded={isEditAssociationListExpanded}
                assocCurrentStep={assocCurrentStep}
                assocSelectedRelationType={assocSelectedRelationType}
                assocSelectedSourceSenseId={assocSelectedSourceSenseId}
                assocSelectedNodeA={assocSelectedNodeA}
                assocSelectedNodeASenseId={assocSelectedNodeASenseId}
                assocSelectedNodeB={assocSelectedNodeB}
                assocSelectedNodeBSenseId={assocSelectedNodeBSenseId}
                assocInsertDirection={assocInsertDirection}
                assocNodeASenseOptions={assocNodeASenseOptions}
                assocInsertRelationAvailable={assocInsertRelationAvailable}
                assocInsertRelationUnavailableReason={assocInsertRelationUnavailableReason}
                assocSearchKeyword={assocSearchKeyword}
                assocSearchAppliedKeyword={assocSearchAppliedKeyword}
                assocSearchLoading={assocSearchLoading}
                assocSearchResults={assocSearchResults}
                assocNodeBView={{ ...assocNodeBView, appliedKeyword: assocNodeBSearchAppliedKeyword }}
                assocNodeBSearchKeyword={assocNodeBSearchKeyword}
                assocPreviewCanvasRef={assocPreviewCanvasRef}
                assocPreviewInfoText={assocPreviewInfoText}
                assocApplyLoading={assocApplyLoading}
                relSymbolSubset={relSymbolSubset}
                relSymbolSuperset={relSymbolSuperset}
                formatNodeSenseDisplay={formatNodeSenseDisplay}
                resolveAssociationDisplayType={resolveAssociationDisplayType}
                setIsEditAssociationListExpanded={setIsEditAssociationListExpanded}
                setAssocSearchKeyword={setAssocSearchKeyword}
                searchAssociationNodes={searchAssociationNodes}
                clearAssocNodeASearch={clearAssocNodeASearch}
                selectAssocNodeA={selectAssocNodeA}
                handleAssocNodeASenseChange={handleAssocNodeASenseChange}
                selectAssocRelationType={selectAssocRelationType}
                submitAssocNodeBSearch={submitAssocNodeBSearch}
                selectAssocNodeB={selectAssocNodeB}
                confirmEditAssociation={confirmEditAssociation}
                goBackAssocStep={goBackAssocStep}
                resetAssociationEditor={resetAssociationEditor}
                startAddEditAssociation={startAddEditAssociation}
                editExistingAssociation={editExistingAssociation}
                removeEditAssociation={removeEditAssociation}
                saveAssociationEdit={saveAssociationEdit}
                onClose={closeEditAssociationModal}
            />
        )}
        {showAssocDeleteDecisionModal && assocDeleteDecisionContext && (
            <AdminAssocDeleteDecisionModal
                assocDeleteDecisionContext={assocDeleteDecisionContext}
                assocDeleteDecisionAction={assocDeleteDecisionAction}
                assocDeleteApplying={assocDeleteApplying}
                editingAssociationNode={editingAssociationNode}
                assocDeleteSelectedTarget={assocDeleteSelectedTarget}
                assocDeleteReplacementDisplay={assocDeleteReplacementDisplay}
                shouldShowAssocDeleteSearch={shouldShowAssocDeleteSearch}
                assocDeleteSearchKeyword={assocDeleteSearchKeyword}
                assocDeleteSearchAppliedKeyword={assocDeleteSearchAppliedKeyword}
                assocDeleteSearchResults={assocDeleteSearchResults}
                assocDeleteSearchLoading={assocDeleteSearchLoading}
                formatNodeSenseDisplay={formatNodeSenseDisplay}
                resolveDecisionPairSideDisplay={resolveDecisionPairSideDisplay}
                resolveDecisionCurrentDisplay={resolveDecisionCurrentDisplay}
                setAssocDeleteDecisionAction={setAssocDeleteDecisionAction}
                setAssocDeleteSearchKeyword={setAssocDeleteSearchKeyword}
                setAssocDeleteSelectedTarget={setAssocDeleteSelectedTarget}
                searchAssocDeleteTargets={searchAssocDeleteTargets}
                confirmAssocDeleteDecision={confirmAssocDeleteDecision}
                onClearSearch={clearAssocDeleteSearch}
                onClose={closeAssocDeleteDecisionModal}
            />
        )}
    </>
);

export default AdminNodesFeature;
