export const FORMULA_GROUPS = Object.freeze([
  {
    key: 'structure',
    label: '结构',
    shortLabel: 'ƒx',
    items: [
      { label: '分式', preview: '\\frac{a}{b}', insert: '\\frac{a}{b}', selection: [6, 7] },
      { label: '平方根', preview: '\\sqrt{x}', insert: '\\sqrt{x}', selection: [6, 7] },
      { label: 'n 次根', preview: '\\sqrt[n]{x}', insert: '\\sqrt[n]{x}', selection: [6, 7] },
      { label: '对数', preview: '\\log_{a}{x}', insert: '\\log_{a}{x}', selection: [6, 7] },
      { label: '自然对数', preview: '\\ln{x}', insert: '\\ln{x}', selection: [4, 5] },
      { label: '指数', preview: '\\exp\\left(x\\right)', insert: '\\exp\\left(x\\right)', selection: [10, 11] },
      { label: 'sin', preview: '\\sin{x}', insert: '\\sin{x}', selection: [5, 6] },
      { label: 'cos', preview: '\\cos{x}', insert: '\\cos{x}', selection: [5, 6] },
      { label: 'tan', preview: '\\tan{x}', insert: '\\tan{x}', selection: [5, 6] },
      { label: '上标', preview: 'x^{n}', insert: 'x^{n}', selection: [0, 1] },
      { label: '下标', preview: 'x_{i}', insert: 'x_{i}', selection: [0, 1] },
      { label: '求和', preview: '\\sum_{i=1}^{n}', insert: '\\sum_{i=1}^{n}', selection: [11, 12] },
      { label: '积分', preview: '\\int_{a}^{b}', insert: '\\int_{a}^{b}', selection: [6, 7] },
      { label: '矩阵', preview: '\\begin{pmatrix}a & b\\\\c & d\\end{pmatrix}', insert: '\\begin{pmatrix}a & b\\\\c & d\\end{pmatrix}', selection: [16, 17] },
      { label: '分段', preview: '\\begin{cases}x^2 & x>0\\\\0 & x\\leq 0\\end{cases}', insert: '\\begin{cases}x^2 & x>0\\\\0 & x\\leq 0\\end{cases}', selection: [13, 16] }
    ]
  },
  {
    key: 'greek',
    label: '希腊',
    shortLabel: 'αβΓΩ',
    items: [
      { label: 'α', insert: '\\alpha', preview: '\\alpha' },
      { label: 'β', insert: '\\beta', preview: '\\beta' },
      { label: 'γ', insert: '\\gamma', preview: '\\gamma' },
      { label: 'δ', insert: '\\delta', preview: '\\delta' },
      { label: 'ε', insert: '\\epsilon', preview: '\\epsilon' },
      { label: 'ζ', insert: '\\zeta', preview: '\\zeta' },
      { label: 'η', insert: '\\eta', preview: '\\eta' },
      { label: 'θ', insert: '\\theta', preview: '\\theta' },
      { label: 'ι', insert: '\\iota', preview: '\\iota' },
      { label: 'κ', insert: '\\kappa', preview: '\\kappa' },
      { label: 'λ', insert: '\\lambda', preview: '\\lambda' },
      { label: 'μ', insert: '\\mu', preview: '\\mu' },
      { label: 'ν', insert: '\\nu', preview: '\\nu' },
      { label: 'ξ', insert: '\\xi', preview: '\\xi' },
      { label: 'ο', insert: 'ο', preview: 'ο' },
      { label: 'π', insert: '\\pi', preview: '\\pi' },
      { label: 'ρ', insert: '\\rho', preview: '\\rho' },
      { label: 'σ', insert: '\\sigma', preview: '\\sigma' },
      { label: 'τ', insert: '\\tau', preview: '\\tau' },
      { label: 'υ', insert: '\\upsilon', preview: '\\upsilon' },
      { label: 'φ', insert: '\\phi', preview: '\\phi' },
      { label: 'χ', insert: '\\chi', preview: '\\chi' },
      { label: 'ψ', insert: '\\psi', preview: '\\psi' },
      { label: 'ω', insert: '\\omega', preview: '\\omega' },
      { label: 'Α', insert: 'Α', preview: 'Α' },
      { label: 'Β', insert: 'Β', preview: 'Β' },
      { label: 'Γ', insert: '\\Gamma', preview: '\\Gamma' },
      { label: 'Δ', insert: '\\Delta', preview: '\\Delta' },
      { label: 'Ε', insert: 'Ε', preview: 'Ε' },
      { label: 'Ζ', insert: 'Ζ', preview: 'Ζ' },
      { label: 'Η', insert: 'Η', preview: 'Η' },
      { label: 'Ξ', insert: '\\Xi', preview: '\\Xi' },
      { label: 'Θ', insert: '\\Theta', preview: '\\Theta' },
      { label: 'Ι', insert: 'Ι', preview: 'Ι' },
      { label: 'Κ', insert: 'Κ', preview: 'Κ' },
      { label: 'Λ', insert: '\\Lambda', preview: '\\Lambda' },
      { label: 'Μ', insert: 'Μ', preview: 'Μ' },
      { label: 'Ν', insert: 'Ν', preview: 'Ν' },
      { label: 'Ο', insert: 'Ο', preview: 'Ο' },
      { label: 'Π', insert: '\\Pi', preview: '\\Pi' },
      { label: 'Ρ', insert: 'Ρ', preview: 'Ρ' },
      { label: 'Σ', insert: '\\Sigma', preview: '\\Sigma' },
      { label: 'Τ', insert: 'Τ', preview: 'Τ' },
      { label: 'Υ', insert: '\\Upsilon', preview: '\\Upsilon' },
      { label: 'Φ', insert: '\\Phi', preview: '\\Phi' },
      { label: 'Χ', insert: 'Χ', preview: 'Χ' },
      { label: 'Ψ', insert: '\\Psi', preview: '\\Psi' },
      { label: 'Ω', insert: '\\Omega', preview: '\\Omega' }
    ]
  },
  {
    key: 'operators',
    label: '运算',
    shortLabel: '±×∫',
    items: [
      { label: '+', insert: '+', preview: '+' },
      { label: '-', insert: '-', preview: '-' },
      { label: '±', insert: '\\pm', preview: '\\pm' },
      { label: '∓', insert: '\\mp', preview: '\\mp' },
      { label: '×', insert: '\\times', preview: '\\times' },
      { label: '÷', insert: '\\div', preview: '\\div' },
      { label: '·', insert: '\\cdot', preview: '\\cdot' },
      { label: '∗', insert: '\\ast', preview: '\\ast' },
      { label: '∘', insert: '\\circ', preview: '\\circ' },
      { label: '∑', insert: '\\sum', preview: '\\sum' },
      { label: '∏', insert: '\\prod', preview: '\\prod' },
      { label: '∫', insert: '\\int', preview: '\\int' },
      { label: '∮', insert: '\\oint', preview: '\\oint' },
      { label: '∐', insert: '\\coprod', preview: '\\coprod' },
      { label: '⊗', insert: '\\otimes', preview: '\\otimes' },
      { label: '⊕', insert: '\\oplus', preview: '\\oplus' }
    ]
  },
  {
    key: 'relations',
    label: '关系',
    shortLabel: '≤⊂⊃',
    items: [
      { label: '=', insert: '=', preview: '=' },
      { label: '≠', insert: '\\neq', preview: '\\neq' },
      { label: '<', insert: '<', preview: '<' },
      { label: '>', insert: '>', preview: '>' },
      { label: '≤', insert: '\\leq', preview: '\\leq' },
      { label: '≥', insert: '\\geq', preview: '\\geq' },
      { label: '≈', insert: '\\approx', preview: '\\approx' },
      { label: '≡', insert: '\\equiv', preview: '\\equiv' },
      { label: '∝', insert: '\\propto', preview: '\\propto' },
      { label: '∈', insert: '\\in', preview: '\\in' },
      { label: '∉', insert: '\\notin', preview: '\\notin' },
      { label: '⊂', insert: '\\subset', preview: '\\subset' },
      { label: '⊆', insert: '\\subseteq', preview: '\\subseteq' },
      { label: '⊃', insert: '\\supset', preview: '\\supset' },
      { label: '⊇', insert: '\\supseteq', preview: '\\supseteq' },
      { label: '⊊', insert: '\\subsetneq', preview: '\\subsetneq' },
      { label: '⊋', insert: '\\supsetneq', preview: '\\supsetneq' }
    ]
  },
  {
    key: 'arrows',
    label: '箭头',
    shortLabel: '←→↦',
    items: [
      { label: '←', insert: '\\leftarrow', preview: '\\leftarrow' },
      { label: '→', insert: '\\rightarrow', preview: '\\rightarrow' },
      { label: '↔', insert: '\\leftrightarrow', preview: '\\leftrightarrow' },
      { label: '⇐', insert: '\\Leftarrow', preview: '\\Leftarrow' },
      { label: '⇒', insert: '\\Rightarrow', preview: '\\Rightarrow' },
      { label: '⇔', insert: '\\Leftrightarrow', preview: '\\Leftrightarrow' },
      { label: '↦', insert: '\\mapsto', preview: '\\mapsto' },
      { label: '⟵', insert: '\\longleftarrow', preview: '\\longleftarrow' },
      { label: '⟶', insert: '\\longrightarrow', preview: '\\longrightarrow' },
      { label: '⟺', insert: '\\Longleftrightarrow', preview: '\\Longleftrightarrow' }
    ]
  },
  {
    key: 'special',
    label: '特殊',
    shortLabel: '∅∞ℵ',
    items: [
      { label: '∂', insert: '\\partial', preview: '\\partial' },
      { label: '∇', insert: '\\nabla', preview: '\\nabla' },
      { label: '∀', insert: '\\forall', preview: '\\forall' },
      { label: '∃', insert: '\\exists', preview: '\\exists' },
      { label: '∅', insert: '\\emptyset', preview: '\\emptyset' },
      { label: '∩', insert: '\\cap', preview: '\\cap' },
      { label: '∪', insert: '\\cup', preview: '\\cup' },
      { label: '∧', insert: '\\land', preview: '\\land' },
      { label: '∨', insert: '\\lor', preview: '\\lor' },
      { label: '∠', insert: '\\angle', preview: '\\angle' },
      { label: '∞', insert: '\\infty', preview: '\\infty' },
      { label: '°', insert: '\\degree', preview: '\\degree' },
      { label: '′', insert: '\\prime', preview: '\\prime' },
      { label: '…', insert: '\\ldots', preview: '\\ldots' },
      { label: '∴', insert: '\\therefore', preview: '\\therefore' },
      { label: '∵', insert: '\\because', preview: '\\because' },
      { label: 'ℵ', insert: '\\aleph', preview: '\\aleph' },
      { label: 'ℜ', insert: '\\Re', preview: '\\Re' },
      { label: 'ℑ', insert: '\\Im', preview: '\\Im' }
    ]
  }
]);

export const FORMULA_DISPLAY_MODES = Object.freeze([
  { key: 'inline', label: '行内公式' },
  { key: 'block', label: '块公式' }
]);
